[package]
name = "coding-survivor"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
raylib = "5.0.2"
ollama-rs = "0.2.6"
tokio = "1.44.1"
noise = "0.9.0"
rand = "0.9.0"
rayon = "1.10.0"

[features]
dev-only = []
